
debug: false

spring.datasource:
  url: jdbc:mysql://dev_db_local/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  username: test
  password: 123456

#mybatis:
#  mapperLocations: classpath:com/flythinker.springboot.sample.cmdtool.mapper/*.xml
#  typeAliasesPackage: com.flythinker.springboot.sample.cmdtool.model

spring.redis:
  database: 0
  host: dev_redis_local
  port: 6379
  password: 12345678901234567890
