
debug: false

server:
  port: 9090
  address: 127.0.0.1
  context-path: /

spring.thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
#spring.thymeleaf.content-type=text/html
  cache: false


spring.datasource:
  url: jdbc:mysql://dev_db_local/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  username: test
  password: 123456

#mybatis:
#  mapperLocations: classpath:com/flythinker.springboot.sample.cmdtool.mapper/*.xml
#  typeAliasesPackage: com.flythinker.springboot.sample.cmdtool.model

spring.redis:
  database: 0
  host: dev_redis_local
  port: 6379
  password: 12345678901234567890

management:
  security:
    enabled: false #关掉安全认证
#  port: 9091 #管理端口调整成1101
  context-path: /admin #actuator的访问路径　　

server.servlet.session:
  #cookie.comment= # Comment for the session cookie.
  #cookie.domain= # Domain for the session cookie.
  #cookie.max-age= # Maximum age of the session cookie. If a duration suffix is not specified, seconds will be used.
  cookie.name: _season_score_session
  cookie.path: /
  tracking-modes: cookie

spring.session:
  redis.cleanup-cron: 0 * * * * *
  redis.flush-mode: on-save
  redis.namespace: season_score:session
  store-type: redis

